
server.port: 8082


logging.level.org: DEBUG
logging.level.io: DEBUG

management:
  metrics:
    distribution.percentiles.hystrix: 0.90,0.99,0.995
    distribution.percentiles-histogram.hystrix: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:

      enabled: true
    hystrix:
      enabled: true
    prometheus:
      enabled: true

#management.metrics.export.datadog:
#  enabled: true
management.metrics.export.prometheus:
  enabled: true

#management.metrics.export.statsd:
#  enabled: true
#  flavor: datadog
